import React, { useEffect, useMemo, useState } from 'react'
import './healthcare-demo.css'

const Icon = ({ name }) => {
  const paths = {
    arrow: <><path d="M5 12h14"/><path d="m15 8 4 4-4 4"/></>,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,
    shield: <path d="M12 3 4.5 6v5.2c0 4.7 3.2 8.1 7.5 9.8 4.3-1.7 7.5-5.1 7.5-9.8V6L12 3Z"/>,
    check: <path d="m5 12 4 4L19 6"/>,
    close: <path d="m6 6 12 12M18 6 6 18"/>,
    user: <><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,
    pulse: <path d="M3 12h4l2-5 4 10 2-5h6"/>,
    lock: <><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,
    chat: <path d="M4 5h16v12H8l-4 4V5Z"/>,
  }
  return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>
}

const services = [
  ['Primary Care','Routine visits, chronic-condition support, and coordinated referrals.','Maya Chen, MD · Daniel Brooks, MD'],
  ['Family Medicine','Whole-family care across adult life stages and common concerns.','Maya Chen, MD'],
  ['Pediatrics','Well-child visits, developmental care, and same-day pediatric concerns.','Elena Ruiz, MD'],
  ["Women’s Health",'Preventive visits, reproductive health, and ongoing wellness support.','Claire Bennett, WHNP-BC'],
  ['Dermatology','Evaluation of common skin concerns and preventive skin checks.','Omar Haddad, MD'],
  ['Behavioral Health','Administrative pathways for therapy consultations and ongoing visits.','Naomi Cole, LCSW'],
  ['Preventive Care','Annual wellness visits, screenings, and personalized prevention planning.','Primary care team'],
]

const providers = [
  { id:'maya', name:'Maya Chen, MD', credentials:'MD, FAAFP', specialty:'Family Medicine', image:'/assets/provider-maya-chen.webp', bio:'Board-certified family physician focused on preventive care, continuity, and practical health planning for adults and families.', languages:'English, Mandarin', insurance:'Sample Health PPO, Horizon Choice, Unity Plus', types:['In-person','Video visit','Annual wellness'], next:'Tue · 9:30 AM' },
  { id:'daniel', name:'Daniel Brooks, MD', credentials:'MD, FACP', specialty:'Primary Care', image:'/assets/provider-daniel-brooks.webp', bio:'Internal medicine physician providing evidence-informed primary care and coordinated specialist referrals for adults.', languages:'English, Spanish', insurance:'Sample Health PPO, Unity Plus, Medicare demo', types:['In-person','Video visit','Follow-up'], next:'Mon · 2:00 PM' },
  { id:'elena', name:'Elena Ruiz, MD', credentials:'MD, FAAP', specialty:'Pediatrics', image:'/assets/provider-elena-ruiz.webp', bio:'Pediatrician supporting children and families through well-child visits, preventive care, and common pediatric concerns.', languages:'English, Spanish', insurance:'Sample Health PPO, FamilyCare Demo, Horizon Choice', types:['In-person','Well-child visit','Same-day visit'], next:'Wed · 10:15 AM' },
  { id:'claire', name:'Claire Bennett, WHNP-BC', credentials:'MSN, WHNP-BC', specialty:"Women’s Health", image:'/assets/provider-claire-bennett.webp', bio:'Women’s health nurse practitioner focused on accessible preventive care and collaborative, patient-centered conversations.', languages:'English, French', insurance:'Sample Health PPO, Horizon Choice, Unity Plus', types:['In-person','Video visit','Preventive visit'], next:'Thu · 8:45 AM' },
  { id:'omar', name:'Omar Haddad, MD', credentials:'MD, FAAD', specialty:'Dermatology', image:'/assets/provider-omar-haddad.webp', bio:'Board-certified dermatologist offering evaluation pathways for common skin concerns and preventive skin examinations.', languages:'English, Arabic', insurance:'Sample Health PPO, Horizon Choice', types:['In-person','Skin check','New concern'], next:'Fri · 11:00 AM' },
  { id:'naomi', name:'Naomi Cole, LCSW', credentials:'LCSW', specialty:'Behavioral Health', image:'/assets/provider-naomi-cole.webp', bio:'Licensed clinical social worker providing a welcoming administrative pathway for consultation and ongoing therapy visits.', languages:'English', insurance:'Sample Health PPO, Mindful Network Demo, Self-pay', types:['Video visit','In-person','Consultation'], next:'Tue · 1:30 PM' },
]

const reasons = {
  'Routine checkup':'Primary Care', 'Annual wellness visit':'Family Medicine', 'Child wellness visit':'Pediatrics',
  "Women’s preventive visit":"Women’s Health", 'Skin concern':'Dermatology', 'Therapy consultation':'Behavioral Health',
}

const slots = ['9:00 AM','10:30 AM','1:00 PM','2:30 PM','4:00 PM']
const CALENDAR_URL = 'https://calendar.app.google/1tdYCWw6gwfTx3E56'
const getToday = () => new Date().toISOString().slice(0, 10)
const getDemoDate = () => {
  const date = new Date()
  date.setDate(date.getDate() + 7)
  return date.toISOString().slice(0, 10)
}

function DemoNotice(){return <div className="hc-demo-notice"><a href="/">← Return to portfolio</a><b>CONNECTIVESTACK LIVE DEMO</b><span>Fictional clinic. All providers, patients, insurance, pricing, and medical information are simulated. Do not enter real PHI.</span></div>}

function BookingFlow({ initialProvider, onClose }) {
  const [step,setStep]=useState(initialProvider ? 4 : 1)
  const [data,setData]=useState(()=>({patientType:'New patient',reason:'Routine checkup',specialty:initialProvider?.specialty||'Primary Care',provider:initialProvider?.id||'maya',appointmentType:initialProvider?.types[0]||'In-person',date:getDemoDate(),time:'9:00 AM',payment:'Insurance',name:'Demo Patient',email:'demo@example.com',phone:'(555) 010-2026',plan:'Sample Health PPO',member:'DEMO-48291'}))
  const set=(key,value)=>setData(current=>({...current,[key]:value}))
  const recommended=useMemo(()=>providers.find(p=>p.specialty===data.specialty)||providers[0],[data.specialty])
  const chosen=providers.find(p=>p.id===data.provider)||recommended
  const next=()=>setStep(value=>Math.min(8,value+1))
  const back=()=>setStep(value=>Math.max(1,value-1))
  const selectReason=value=>{const specialty=reasons[value];setData(current=>({...current,reason:value,specialty,provider:(providers.find(p=>p.specialty===specialty)||providers[0]).id}))}
  return <div className="hc-modal" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="hc-booking" role="dialog" aria-modal="true" aria-labelledby="hc-booking-title">
    <button type="button" className="hc-close" onClick={onClose} aria-label="Close booking workflow"><Icon name="close"/></button>
    <div className="hc-booking-head"><small>SIMULATED SCHEDULING WORKFLOW</small><h2 id="hc-booking-title">{step===8?'Appointment request confirmed':'Book an appointment'}</h2><div>{[1,2,3,4,5,6,7,8].map(n=><i className={n<=step?'active':''} key={n}/>)}</div></div>
    {step===1&&<div className="hc-step"><h3>Have you visited Harborline Medical before?</h3><div className="hc-choice-grid">{['New patient','Existing patient'].map(x=><button className={data.patientType===x?'selected':''} onClick={()=>set('patientType',x)} key={x}><Icon name="user"/><strong>{x}</strong><span>{x==='New patient'?'Start a simulated registration':'Use a fictional returning-patient path'}</span></button>)}</div></div>}
    {step===2&&<div className="hc-step"><h3>What type of visit are you looking for?</h3><div className="hc-option-list">{Object.keys(reasons).map(x=><button className={data.reason===x?'selected':''} onClick={()=>selectReason(x)} key={x}><span>{x}</span><small>{reasons[x]}</small><Icon name="arrow"/></button>)}</div></div>}
    {step===3&&<div className="hc-step"><h3>Best-fit specialty</h3><div className="hc-route-result"><span>RECOMMENDED FROM YOUR SELECTION</span><strong>{data.specialty}</strong><p>Your visit reason maps to this simulated clinic service. You can adjust it below.</p></div><label>Specialty<select value={data.specialty} onChange={e=>set('specialty',e.target.value)}>{[...new Set(providers.map(p=>p.specialty))].map(x=><option key={x}>{x}</option>)}</select></label></div>}
    {step===4&&<div className="hc-step"><h3>Choose your provider</h3><div className="hc-recommended"><img src={recommended.image} alt=""/><div><small>RECOMMENDED PROVIDER</small><strong>{recommended.name}</strong><span>{recommended.specialty} · {recommended.next}</span></div></div><div className="hc-provider-options">{providers.filter(p=>p.specialty===data.specialty||p.id===recommended.id).map(p=><button className={data.provider===p.id?'selected':''} onClick={()=>{set('provider',p.id);set('appointmentType',p.types[0])}} key={p.id}>{p.name}<small>{p.types.join(' · ')}</small></button>)}</div><details><summary>Choose another provider</summary><select value={data.provider} onChange={e=>set('provider',e.target.value)}>{providers.map(p=><option value={p.id} key={p.id}>{p.name} · {p.specialty}</option>)}</select></details></div>}
    {step===5&&<div className="hc-step"><h3>Select appointment type and time</h3><div className="hc-segment">{chosen.types.map(x=><button className={data.appointmentType===x?'selected':''} onClick={()=>set('appointmentType',x)} key={x}>{x}</button>)}</div><label>Date<input type="date" min={getToday()} value={data.date} onChange={e=>set('date',e.target.value)}/></label><div className="hc-time-grid">{slots.map(x=><button className={data.time===x?'selected':''} onClick={()=>set('time',x)} key={x}>{x}</button>)}</div></div>}
    {step===6&&<div className="hc-step"><h3>Patient contact information</h3><p className="hc-step-note">Demo only. Use fictional information and do not enter medical details or real PHI.</p><div className="hc-fields"><label>Full name<input value={data.name} onChange={e=>set('name',e.target.value)}/></label><label>Email<input type="email" value={data.email} onChange={e=>set('email',e.target.value)}/></label><label>Phone<input value={data.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Preferred contact<select><option>Email</option><option>SMS</option><option>Phone</option></select></label></div></div>}
    {step===7&&<div className="hc-step"><h3>Insurance or self-pay</h3><div className="hc-segment">{['Insurance','Self-pay'].map(x=><button className={data.payment===x?'selected':''} onClick={()=>set('payment',x)} key={x}>{x}</button>)}</div>{data.payment==='Insurance'?<div className="hc-fields"><label>Insurance plan<select value={data.plan} onChange={e=>set('plan',e.target.value)}><option>Sample Health PPO</option><option>Horizon Choice Demo</option><option>Unity Plus Sample</option></select></label><label>Demo member ID<input value={data.member} onChange={e=>set('member',e.target.value)}/></label></div>:<div className="hc-selfpay"><strong>Transparent self-pay example</strong><p>{data.appointmentType}: $145 estimated demo price</p></div>}<p className="hc-step-note">Simulated benefits information only. No real insurance data is submitted or verified.</p></div>}
    {step===8&&<div className="hc-confirm"><span><Icon name="check"/></span><small>SIMULATED CONFIRMATION</small><h3>Your demo request is complete.</h3><div><p><b>Provider</b>{chosen.name}</p><p><b>Specialty</b>{chosen.specialty}</p><p><b>Appointment</b>{data.appointmentType}</p><p><b>Demo date and time</b>{data.date} · {data.time}</p><p><b>Payment</b>{data.payment==='Insurance'?`${data.plan} · Verification pending`:'Self-pay'}</p></div><p>No real appointment was created. A production workflow could send email and SMS confirmations, update the patient record, notify the care team, and schedule reminders.</p><div className="hc-confirm-actions"><a href={CALENDAR_URL} target="_blank" rel="noreferrer">Book a real discovery call</a><button onClick={onClose}>Return to demo</button></div></div>}
    {step<8&&<div className="hc-booking-actions"><button disabled={step===1} onClick={back}>Back</button><button onClick={next}>{step===7?'Confirm demo appointment':'Continue'} <Icon name="arrow"/></button></div>}
  </section></div>
}

function CostEstimator(){
  const prices={'Primary care visit':180,'Specialist visit':320,'Annual wellness visit':240,'Dermatology consultation':290,'Behavioral health consultation':210}
  const [service,setService]=useState('Primary care visit'),[payment,setPayment]=useState('Insurance'),[copay,setCopay]=useState(30),[coinsurance,setCoinsurance]=useState(20),[deductible,setDeductible]=useState(650)
  const rate=prices[service]
  const estimate=payment==='Self-pay'?Math.round(rate*.8):Math.min(rate,Math.round(Math.max(copay,Math.min(rate,deductible)+Math.max(0,rate-deductible)*coinsurance/100)))
  return <div className="hc-estimator"><div className="hc-estimator-controls"><label>Appointment or service<select value={service} onChange={e=>setService(e.target.value)}>{Object.keys(prices).map(x=><option key={x}>{x}</option>)}</select></label><label>Payment method<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Insurance</option><option>Self-pay</option></select></label>{payment==='Insurance'&&<><label>Copay ($)<input type="number" min="0" value={copay} onChange={e=>setCopay(+e.target.value)}/></label><label>Coinsurance (%)<input type="number" min="0" max="100" value={coinsurance} onChange={e=>setCoinsurance(+e.target.value)}/></label><label>Deductible remaining ($)<input type="number" min="0" value={deductible} onChange={e=>setDeductible(+e.target.value)}/></label></>}</div><div className="hc-estimate-result"><small>ESTIMATED PATIENT RESPONSIBILITY</small><strong>${estimate}<span> demo estimate</span></strong><div><i style={{width:`${Math.min(100,estimate/rate*100)}%`}}/></div><p>Fictional allowed amount: ${rate}</p><em>This estimate is for demonstration purposes only. Actual patient responsibility depends on eligibility, benefits, provider network status, contracted rates, claim processing, and the specific insurance plan.</em></div></div>
}

function FAQ(){const [open,setOpen]=useState(false);const [messages,setMessages]=useState([{from:'bot',text:'Hi. I can help with clinic hours, scheduling, insurance examples, and visit preparation. I cannot provide medical advice.'}]);const answers={'Office hours':'Monday through Friday, 8:00 AM to 6:00 PM, and Saturday, 9:00 AM to 1:00 PM. Demo information only.','Accepted insurance':'The demo uses fictional examples such as Sample Health PPO, Horizon Choice, and Unity Plus. Production acceptance varies by provider and plan.','Prepare for a visit':'Bring identification, your current insurance card if applicable, and a medication list. For this public demo, do not enter or upload real medical information.','Reschedule or cancel':'A production portal could allow secure rescheduling. This fictional clinic shows a 24-hour cancellation policy.','Self-pay pricing':'Sample self-pay amounts are shown in the estimator. Actual pricing would be confirmed by the clinic.','Medical question':'I cannot assess symptoms, diagnose conditions, recommend medication, or give individualized medical advice. Contact a licensed healthcare professional. For a medical emergency, call 911 or local emergency services.'};const ask=q=>setMessages(m=>[...m,{from:'user',text:q},{from:'bot',text:answers[q]}]);return <><button type="button" className="hc-chat-launch" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="hc-chat-panel"><Icon name={open?'close':'chat'}/><span>{open?'Close':'Ask the clinic assistant'}</span></button>{open&&<aside id="hc-chat-panel" className="hc-chat" aria-label="Harborline clinic assistant"><header><div><b>Harborline Assistant</b><span><i/> Administrative demo</span></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close clinic assistant"><Icon name="close"/></button></header><div className="hc-chat-body">{messages.map((m,i)=><p className={m.from} key={i}>{m.text}</p>)}</div><div className="hc-chat-options">{Object.keys(answers).map(x=><button type="button" onClick={()=>ask(x)} key={x}>{x}</button>)}</div></aside>}</>}

export default function HealthcareDemo(){
  const [booking,setBooking]=useState(null),[profile,setProfile]=useState(null),[status,setStatus]=useState('Coverage Active')
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('is-visible')),{threshold:.12});document.querySelectorAll('.hc-trust,.hc-section,.hc-final,.hc-hero-card').forEach(element=>{element.classList.add('hc-reveal');observer.observe(element)});return()=>observer.disconnect()},[])
  useEffect(()=>{if(!booking&&!profile)return undefined;const close=event=>{if(event.key==='Escape'){setBooking(null);setProfile(null)}};document.body.style.overflow='hidden';window.addEventListener('keydown',close);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',close)}},[booking,profile])
  return <div className="hc-page"><DemoNotice/><header className="hc-header"><a href="#home" className="hc-brand"><span className="hc-brand-mark"><Icon name="pulse"/></span><div><b>HARBORLINE MEDICAL</b><small>CONNECTED CARE GROUP</small></div></a><nav><a href="#services">Services</a><a href="#providers">Providers</a><a href="#benefits">Insurance</a><a href="#security">Privacy</a><a href="#workflow">How it works</a></nav><a className="hc-header-book" href={CALENDAR_URL} target="_blank" rel="noreferrer">Book a discovery call</a></header>
    <main><section className="hc-hero" id="home"><img src="/assets/healthcare-hero-v1.webp" alt="Fictional modern Harborline Medical clinic"/><div className="hc-hero-overlay"/><div className="hc-hero-copy"><span>MODERN CARE · CONNECTED OPERATIONS</span><h1>Care starts with a clearer digital experience.</h1><p>Find the right provider, understand simulated benefits, estimate costs, and schedule through one thoughtfully connected patient journey.</p><div><button onClick={()=>setBooking('start')}>Try the booking workflow <Icon name="arrow"/></button><a href={CALENDAR_URL} target="_blank" rel="noreferrer">Book a discovery call</a></div><small><Icon name="shield"/> Demo only. Do not enter real health or insurance information.</small></div><div className="hc-hero-card"><small>SMART ROUTING PREVIEW</small><div><i className="done"/><span>Visit reason</span><b>Preventive care</b></div><div><i className="done"/><span>Specialty</span><b>Family medicine</b></div><div><i/><span>Best-fit provider</span><b>Maya Chen, MD</b></div><button onClick={()=>setBooking(providers[0])}>Try provider routing</button></div></section>
    <section className="hc-trust"><div><Icon name="calendar"/><b>Multi-provider scheduling</b><span>Route by need and availability</span></div><div><Icon name="shield"/><b>Privacy-conscious intake</b><span>Minimum-necessary data design</span></div><div><Icon name="pulse"/><b>Benefits experience</b><span>Eligibility and cost concepts</span></div><div><Icon name="check"/><b>Automated follow-up</b><span>Confirmation and reminders</span></div></section>
    <section className="hc-section hc-services" id="services"><div className="hc-heading"><div><span>CARE PATHWAYS</span><h2>One clinic, multiple specialties, relevant next steps.</h2></div><p>Each service connects the visitor to an appropriate fictional provider, appointment type, and intake path.</p></div><div className="hc-service-grid">{services.map(([name,copy,team],i)=><article key={name}><span>0{i+1}</span><div><h3>{name}</h3><p>{copy}</p><small>{team}</small></div><button onClick={()=>{const p=providers.find(x=>x.specialty===name)||providers[0];setBooking(p)}} aria-label={`Try ${name} routing`}><Icon name="arrow"/></button></article>)}</div></section>
    <section className="hc-section hc-providers" id="providers"><div className="hc-heading"><div><span>PROVIDER DIRECTORY</span><h2>Choose by specialty, language, or visit type.</h2></div><p>Every provider profile and schedule is fictional, demonstrating how a real clinic could support personalized discovery and routing.</p></div><div className="hc-provider-grid">{providers.map(p=><article key={p.id}><img src={p.image} alt={`Fictional provider ${p.name}`} loading="lazy"/><div><small>{p.specialty}</small><h3>{p.name}</h3><b>{p.credentials}</b><p>{p.bio}</p><dl><div><dt>Languages</dt><dd>{p.languages}</dd></div><div><dt>Next available</dt><dd>{p.next}</dd></div></dl><span>{p.types.join(' · ')}</span><footer><button onClick={()=>setProfile(p)}>View profile</button><a href={CALENDAR_URL} target="_blank" rel="noreferrer">Book a discovery call</a></footer></div></article>)}</div></section>
    <section className="hc-section hc-benefits" id="benefits"><div className="hc-heading light"><div><span>SIMULATED ELIGIBILITY</span><h2>Make insurance information easier to understand.</h2></div><p>This interface demonstrates benefits communication only. It does not verify real coverage or process real insurance data.</p></div><div className="hc-benefits-layout"><div className="hc-status-panel"><span>ELIGIBILITY WORKFLOW STATUS</span><div className="hc-status-tabs">{['Coverage Active','Verification Pending','Verified','Additional Information Required','Self-Pay'].map(x=><button className={status===x?'active':''} onClick={()=>setStatus(x)} key={x}>{x}</button>)}</div><div className="hc-status-result"><i/><small>CURRENT SIMULATED STATUS</small><strong>{status}</strong><p>{status==='Coverage Active'?'Sample Health PPO · Effective Jan 1, 2026':status==='Self-Pay'?'Transparent sample pricing selected':'Administrative review step demonstrated'}</p></div></div><div className="hc-benefit-card"><header><div><small>DEMO PLAN</small><strong>Sample Health PPO</strong></div><span>ACTIVE</span></header><div className="hc-benefit-numbers"><p><small>Primary care copay</small><b>$30</b></p><p><small>Specialist copay</small><b>$50</b></p><p><small>Coinsurance</small><b>20%</b></p><p><small>Annual deductible</small><b>$1,500</b></p><p><small>Deductible met</small><b>$850</b></p><p><small>Remaining deductible</small><b>$650</b></p><p><small>Out-of-pocket maximum</small><b>$6,000</b></p></div><small>All values are fictional and shown for interface demonstration.</small></div></div><div className="hc-definitions">{[['COPAY','A fixed amount the patient may pay for a covered healthcare service.'],['COINSURANCE','The percentage of a covered healthcare service the patient may be responsible for after applicable deductible requirements.'],['DEDUCTIBLE','The amount the patient may need to pay toward covered services before the insurance plan begins sharing applicable costs.'],['OUT-OF-POCKET MAXIMUM','The maximum amount the patient may be responsible for paying for covered in-network services during the plan year, subject to plan rules.']].map(([a,b])=><article key={a}><span>{a}</span><p>{b}</p></article>)}</div></section>
    <section className="hc-section hc-cost"><div className="hc-heading"><div><span>COST ESTIMATE DEMO</span><h2>Explore a clearer patient responsibility estimate.</h2></div><p>Switch between fictional insurance and self-pay paths to see how the interface explains estimated costs.</p></div><CostEstimator/></section>
    <section className="hc-section hc-security" id="security"><div className="hc-security-copy"><span>PRIVACY-CONSCIOUS DESIGN</span><h2>Designed with HIPAA-conscious workflows in mind.</h2><p>A production healthcare experience should collect only what is needed, clearly explain consent, protect information in transit and at rest, and limit access based on role and purpose.</p><div>{['Minimum-necessary data collection','Controlled access','Secure transmission','Consent workflows','Privacy-conscious intake','Auditability'].map(x=><span key={x}><Icon name="check"/>{x}</span>)}</div><aside><Icon name="shield"/><p>This public portfolio demo does not collect real protected health information. Production HIPAA compliance depends on the complete technology stack, hosting environment, vendor agreements and BAAs, configuration, security controls, policies, and operational procedures. This demo is not represented as HIPAA Certified or universally HIPAA Compliant.</p></aside></div><div className="hc-security-visual"><div className="hc-lock"><Icon name="lock"/></div><div className="hc-data-flow"><span>Public website</span><i/><span>Consent boundary</span><i/><span>Secure workflow</span><i/><span>Authorized team</span></div><div className="hc-audit"><small>WORKFLOW EVENT LOG · SIMULATED</small><p><b>09:14:02</b> Intake started</p><p><b>09:15:18</b> Consent recorded</p><p><b>09:16:04</b> Route assigned</p><p><b>09:17:31</b> Confirmation queued</p></div></div></section>
    <section className="hc-section hc-workflow" id="workflow"><div className="hc-heading"><div><span>CONNECTED PATIENT JOURNEY</span><h2>More than a website. A coordinated operational flow.</h2></div><p>Every step can connect to the next appropriate system while preserving clear boundaries between public content and sensitive workflows.</p></div><div className="hc-flow">{['Patient visit','Smart intake','Insurance / self-pay','Provider routing','Scheduling','Confirmation','CRM / patient workflow','Follow-up'].map((x,i)=><React.Fragment key={x}><div><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></div>{i<7&&<i><Icon name="arrow"/></i>}</React.Fragment>)}</div></section>
    <section className="hc-final"><div><span>CONNECTIVESTACK HEALTHCARE DEMO</span><h2>Build a patient journey that connects the front door to the workflow behind it.</h2></div><div><p>This fictional concept demonstrates multi-provider scheduling, conditional intake, insurance concepts, estimates, privacy-conscious design, routing, and automation.</p><a href={CALENDAR_URL} target="_blank" rel="noreferrer">Discuss a healthcare project <Icon name="arrow"/></a></div></section></main>
    <footer className="hc-footer"><a href="/">← ConnectiveStack portfolio</a><span>Fictional portfolio demonstration · No real PHI</span><a href={CALENDAR_URL} target="_blank" rel="noreferrer">Book a discovery call</a></footer>
    {booking&&<BookingFlow initialProvider={typeof booking==='object'?booking:null} onClose={()=>setBooking(null)}/>} {profile&&<div className="hc-modal" onMouseDown={e=>e.target===e.currentTarget&&setProfile(null)}><section className="hc-profile" role="dialog" aria-modal="true" aria-labelledby="hc-profile-title"><button type="button" className="hc-close" onClick={()=>setProfile(null)} aria-label="Close provider profile"><Icon name="close"/></button><img src={profile.image} alt={`Fictional provider ${profile.name}`}/><div><small>{profile.specialty}</small><h2 id="hc-profile-title">{profile.name}</h2><b>{profile.credentials}</b><p>{profile.bio}</p><dl><dt>Languages</dt><dd>{profile.languages}</dd><dt>Accepted insurance examples</dt><dd>{profile.insurance}</dd><dt>Appointment types</dt><dd>{profile.types.join(', ')}</dd></dl><a className="hc-profile-calendar" href={CALENDAR_URL} target="_blank" rel="noreferrer">Book a discovery call <Icon name="arrow"/></a></div></section></div>}<FAQ/></div>
}
