import React,{useEffect,useState} from 'react'
import './seo-pages.css'
const SITE='https://connectivestack.com'
const CAL='https://calendar.app.google/1tdYCWw6gwfTx3E56'
const pages={
'website-not-showing-on-google':['Website SEO','Why Your Business Website Is Not Showing Up on Google','A practical guide to indexing, technical SEO, local signals and discoverability when a live business website is difficult to find.','Website Development','/solutions/website-development'],
'hvac-website-not-showing-on-google':['HVAC SEO',"Why Your HVAC Website Isn't Showing Up on Google",'What HVAC companies can check when a website is live but difficult to find in branded or local service searches.','HVAC','/solutions/hvac'],
'hvac-google-business-profile-vs-website':['HVAC SEO','Google Business Profile vs. Website for HVAC Companies','How a strong Google Business Profile and a dedicated HVAC website support different parts of local discovery and conversion.','HVAC','/solutions/hvac'],
'hvac-missed-call-automation':['HVAC Automation','How Missed Call Automation Works for HVAC Companies','A practical customer path from a missed HVAC call to response, qualification, booking, CRM and follow-up.','HVAC','/solutions/hvac'],
'automated-lead-follow-up':['CRM Automation','How Automated Lead Follow-Up Works for Small Businesses','How a new inquiry can move from website form to CRM, owner, response, reminders and a defined fallback path.','CRM Automation','/solutions/crm-automation'],
'website-to-crm-integration':['CRM Integration','How to Connect a Website to a CRM','The core data flow between website forms, CRM contacts, opportunities, calendars, notifications and follow-up.','Integrations','/solutions/integrations'],
'website-form-not-delivering-leads':['Website Troubleshooting',"Why Your Website Form Isn't Delivering Leads",'Where form submissions can fail between the browser, server, email provider, CRM, notification and lead owner.','Integrations','/solutions/integrations'],
'ai-receptionist-small-business':['AI Automation','How an AI Receptionist Can Work for a Small Business','A practical look at AI call handling, qualification, structured data capture, human escalation and workflow boundaries.','AI Automation','/solutions/ai-automation']
}
const sols={
'website-development':['WEBSITE DEVELOPMENT','Websites Built to Turn Attention Into Action','Modern service-business websites with clear customer journeys, technical SEO foundations, lead capture and reliable deployment.'],
'ai-automation':['AI AUTOMATION','Practical AI Automation for Small Businesses','AI workflows for repetitive customer and operational tasks, designed with clear boundaries, fallback logic and human handoff.'],
'crm-automation':['CRM AUTOMATION','CRM and Lead Follow-Up Automation','Connect inquiries to contacts, pipelines, owners, reminders and follow-up so opportunities do not disappear between tools.'],
'integrations':['API INTEGRATIONS','Website, CRM and Business System Integrations','Connect websites, calendars, email, CRM, databases and third-party tools around the actual business process.'],
'hvac':['HVAC SYSTEMS','HVAC Websites and Lead Automation','Connect local discovery, service pages, calls, estimate requests, booking and follow-up into one customer path.'],
'real-estate':['REAL ESTATE SYSTEMS','Real Estate Websites and Lead Routing','Property experiences with buyer intent, agent routing, tour requests, qualification and connected follow-up.'],
'healthcare':['HEALTHCARE SYSTEMS','Healthcare Website and Administrative Workflows','Provider discovery, administrative intake, scheduling and patient routing designed with privacy-conscious workflows in mind.']
}
function Meta({title,desc,path}){useEffect(()=>{document.title=title;const set=(sel,attr,val)=>{let x=document.querySelector(sel);if(x)x.setAttribute(attr,val)};set('meta[name="description"]','content',desc);set('meta[property="og:title"]','content',title);set('meta[property="og:description"]','content',desc);set('meta[property="og:url"]','content',SITE+path);let c=document.querySelector('link[rel="canonical"]');if(c)c.href=SITE+path},[title,desc,path]);return null}
function Head(){return <header className="seo-head"><a href="/" className="seo-logo"><img src="/assets/connective-stack-logo.png" alt="ConnectiveStack"/></a><nav><a href="/#services">Problems I Solve</a><a href="/seo-guides">Guides</a><a href="/ajell-saliba">About AJ</a><a className="seo-pill" href={CAL} target="_blank" rel="noreferrer">Show me the problem</a></nav></header>}
function Foot(){return <footer className="seo-foot"><a href="/"><img src="/assets/connective-stack-logo.png" alt="ConnectiveStack"/></a><p>Websites, CRM, AI automation and integrations built around the problem that needs to be solved.</p><div><a href="/seo-guides">Guides</a><a href="/ajell-saliba">About AJ</a></div></footer>}
export function GuideHub(){const [q,setQ]=useState('');const list=Object.entries(pages).filter(([,p])=>(p[1]+' '+p[2]+' '+p[3]).toLowerCase().includes(q.toLowerCase()));return <><Meta title="Website, CRM and AI Automation Guides | ConnectiveStack" desc="Practical ConnectiveStack guides for website SEO, HVAC lead generation, CRM automation, AI receptionists and business system integrations." path="/seo-guides"/><Head/><main className="seo-main"><section className="seo-hero"><span>PRACTICAL SYSTEM GUIDES</span><h1>Find the problem before adding another tool.</h1><p>Technical guides for service businesses dealing with weak website visibility, lost leads, disconnected CRM workflows, missed calls and manual handoffs.</p><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search website, CRM, HVAC, AI..." aria-label="Search guides"/></section><section className="seo-grid">{list.map(([slug,p])=><article key={slug}><small>{p[0]}</small><h2>{p[1]}</h2><p>{p[2]}</p><a href={'/guides/'+slug}>Read guide</a></article>)}</section></main><Foot/></>}
export function Guide({slug}){const p=pages[slug];if(!p)return <GuideHub/>;return <><Meta title={p[1]+' | ConnectiveStack'} desc={p[2]} path={'/guides/'+slug}/><Head/><main className="seo-main seo-article"><a href="/seo-guides">Back to guides</a><article><span>{p[0]}</span><h1>{p[1]}</h1><p className="lead">{p[2]}</p><h2>Start with what can be verified</h2><p>A visible symptom does not always reveal the layer causing the problem. Check the customer path before deciding whether the fix belongs in the website, search setup, CRM, automation or integration.</p><h2>What to check</h2><ul><li>Can the right customer discover and understand the page?</li><li>Is the primary call, form, estimate or booking action easy to complete?</li><li>Does submitted information reach the correct system and owner?</li><li>Is there a defined response when a webhook, field, notification or human handoff fails?</li></ul><h2>What the system should accomplish</h2><p>The goal is a clear path from customer intent to the next business action. That means fewer silent failures, fewer manual handoffs and enough visibility to understand what happened when something breaks.</p><div className="seo-next"><strong>Related solution</strong><a href={p[4]}>Explore {p[3]}</a></div></article></main><Foot/></>}
export function Solution({slug}){const p=sols[slug];if(!p)return <GuideHub/>;const demo=slug==='hvac'?'/demos/hvac-ai-front-desk':slug==='real-estate'?'/demos/luxury-real-estate':slug==='healthcare'?'/demos/healthcare-patient-experience':null;return <><Meta title={p[1]+' | ConnectiveStack'} desc={p[2]} path={'/solutions/'+slug}/><Head/><main className="seo-main"><section className="seo-hero"><span>{p[0]}</span><h1>{p[1]}</h1><p>{p[2]}</p><div className="seo-actions">{demo&&<a className="primary" href={demo}>Try the live demo</a>}<a href="/seo-guides">Read related guides</a></div></section><section className="seo-grid"><article><small>01</small><h2>Trace the current path</h2><p>Start with the customer action, the information it creates and every handoff that follows.</p></article><article><small>02</small><h2>Fix the actual failure</h2><p>Change the page, routing, workflow or integration that evidence points to instead of adding unnecessary software.</p></article><article><small>03</small><h2>Test edge cases</h2><p>Verify mobile behavior, missing fields, duplicates, failed notifications, retries and human escalation.</p></article><article><small>04</small><h2>Make it measurable</h2><p>Track meaningful customer and operational actions so the business can see where the journey succeeds or stalls.</p></article></section></main><Foot/></>}
export function AboutAjell(){return <><Meta title="Ajell Saliba | Web and AI Automation Specialist | ConnectiveStack" desc="Ajell Saliba, also known as AJ, is the independent web and systems specialist behind ConnectiveStack." path="/ajell-saliba"/><Head/><main className="seo-main seo-about"><section><div><span>AJELL SALIBA / CONNECTIVESTACK</span><h1>Ajell Saliba, Web and AI Automation Specialist</h1><p className="lead">I am Ajell “AJ” Saliba, the independent specialist behind ConnectiveStack. I work across websites, lead routing, CRM, automation, integrations, DNS and deployment.</p><p>My 11 years of professional experience span customer service, sales, quality assurance, team leadership, GoHighLevel operations, website delivery and technical systems work. Clients work directly with me from problem mapping through launch.</p><div className="seo-actions"><a className="primary" href={CAL} target="_blank" rel="noreferrer">Discuss a problem</a><a href="/seo-guides">Read technical guides</a></div></div><img src="/assets/ajell-saliba.webp" alt="Ajell Saliba, web and AI automation specialist behind ConnectiveStack"/></section></main><Foot/></>}
export const guideSlugs=new Set(Object.keys(pages))
export const solutionSlugs=new Set(Object.keys(sols))
