import React,{useEffect,useState} from 'react'
import './seo-pages.css'
const SITE='https://connectivestack.com'
const CAL='https://calendar.app.google/1tdYCWw6gwfTx3E56'
const guides=[
['why-hvac-website-not-showing-on-google','HVAC','Website & SEO',"Why Your HVAC Website Isn't Showing Up on Google",'Indexing, local signals, technical SEO and discoverability for HVAC websites.','/solutions/hvac'],
['hvac-google-business-profile-vs-website','HVAC','Website & SEO','Google Business Profile vs. Website for HVAC Companies','How a strong Google profile and a dedicated website can work together.','/solutions/hvac'],
['hvac-missed-call-automation','HVAC','Calls & Follow-up','What Happens When an HVAC Company Misses a Customer Call?','A practical missed-call workflow for response, qualification, booking and follow-up.','/solutions/hvac'],
['website-not-indexed-google','All','Website & SEO',"Why a Website Exists but Doesn't Appear in Google Search",'What to inspect when a live website is difficult to find by company name or service search.','/solutions/website-systems'],
['website-traffic-no-leads','All','Website & SEO','Website Traffic but No Leads? Check the Conversion Path','Find friction between a visitor landing on a page and becoming an inquiry.','/solutions/website-systems'],
['automated-lead-follow-up','All','Leads & Sales','How Automated Lead Follow-Up Works','Website capture, CRM creation, routing, reminders and fallback logic in plain English.','/solutions/crm-automation'],
['website-to-crm-booking-follow-up','All','Integrations','Website to CRM to Booking to Follow-Up: How the System Works','How data should move through a connected lead journey without repeated manual entry.','/solutions/integrations'],
['crm-vs-spreadsheet-small-business','All','Leads & Sales','CRM vs. Spreadsheet: When Does a Small Business Need a CRM?','When lead ownership, stages, reminders and automation justify moving beyond a spreadsheet.','/solutions/crm-automation'],
['ai-answer-customer-calls','All','AI & Automation','Can AI Answer Customer Calls for a Small Business?','Where AI voice can help, where human escalation matters and what a responsible workflow includes.','/solutions/ai-automation'],
['website-form-not-delivering-leads','All','Integrations',"Why Your Website Form Isn't Delivering Leads",'A troubleshooting path across browser, server, email, CRM and notification layers.','/solutions/integrations']
]
const sols={
'website-systems':['WEBSITE SYSTEMS','Website Systems for Service Businesses','Search-friendly websites built around clear customer actions, lead capture, booking and the technical layer behind the page.'],
'ai-automation':['AI AUTOMATION','Practical AI Automation for Small Businesses','Use AI where it removes repetitive work or improves response time, with boundaries, fallback logic and human handoff.'],
'crm-automation':['CRM AUTOMATION','CRM & Lead Follow-Up Automation','Turn inquiries into visible contacts, opportunities, owners and next actions instead of letting leads stall.'],
'integrations':['INTEGRATIONS','Business System & API Integrations','Connect the tools already used by the business so information reaches the right system or person.'],
'hvac':['HVAC SOLUTIONS','HVAC Websites, Lead Capture & Automation','A connected HVAC customer path across local discovery, service pages, calls, estimate requests, booking and follow-up.'],
'real-estate':['REAL ESTATE SOLUTIONS','Real Estate Websites, Routing & Buyer Journeys','Property experiences that route buyer intent, broker relationships, tour requests and qualification.'],
'healthcare':['HEALTHCARE SOLUTIONS','Healthcare Website & Workflow Systems','Administrative patient journeys for provider discovery, intake and scheduling, designed with privacy-conscious workflows in mind.']
}
function Meta({title,desc,path}){useEffect(()=>{document.title=title;let m=document.querySelector('meta[name="description"]');if(m)m.content=desc;let c=document.querySelector('link[rel="canonical"]');if(c)c.href=SITE+path},[title,desc,path]);return null}
function Head(){return <header className="seo-head"><a href="/"><img src="/assets/connective-stack-logo.png" alt="ConnectiveStack"/></a><nav><a href="/#services">Problems I Solve</a><a href="/resources">Resources</a><a href="/ajell-saliba">About AJ</a><a className="pill" href={CAL} target="_blank" rel="noreferrer">Book a call</a></nav></header>}
function Foot(){return <footer className="seo-foot"><b>ConnectiveStack</b><span>Websites • AI Automation • Integrations</span><a href="/">Home</a></footer>}
export function Resources(){const [cat,setCat]=useState('All');const [q,setQ]=useState('');const cats=['All','Website & SEO','Calls & Follow-up','Leads & Sales','Integrations','AI & Automation'];const shown=guides.filter(g=>(cat==='All'||g[2]===cat)&&(!q||(g[3]+' '+g[4]).toLowerCase().includes(q.toLowerCase())));return <><Meta title="Business Systems Resource Hub | ConnectiveStack" desc="Practical guides for website SEO, lead follow-up, CRM, integrations and AI automation." path="/resources"/><Head/><main className="seo-main"><section className="seo-hero"><span>CONNECTIVESTACK / RESOURCE HUB</span><h1>What problem are you trying to solve?</h1><p>Explore practical answers around websites, leads, CRM, calls and automation instead of digging through a generic blog.</p></section><section className="filters"><input aria-label="Search resources" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search a problem, e.g. website not showing on Google"/><div>{cats.map(x=><button className={cat===x?'on':''} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div></section><section className="seo-grid">{shown.map(g=><article key={g[0]}><small>{g[1]} / {g[2]}</small><h2>{g[3]}</h2><p>{g[4]}</p><a href={'/resources/'+g[0]}>Read the guide →</a></article>)}</section></main><Foot/></>}
export function Guide({slug}){const g=guides.find(x=>x[0]===slug);if(!g)return <Resources/>;return <><Meta title={g[3]+' | ConnectiveStack'} desc={g[4]} path={'/resources/'+slug}/><Head/><main className="seo-main article"><a href="/resources">← Resource Hub</a><article><span>{g[1]} / {g[2]}</span><h1>{g[3]}</h1><p className="lead">{g[4]}</p><h2>Start with the symptom, not the assumption</h2><p>A useful audit separates what can be observed from what still needs diagnosis. Check the customer path end to end before deciding that the problem is design, SEO, automation or a specific tool.</p><h2>What to inspect</h2><ul><li>Discoverability, indexability and the page a customer actually lands on.</li><li>The primary call, form, estimate or booking action on mobile and desktop.</li><li>Whether the submission reaches the correct inbox, CRM, owner or calendar.</li><li>Fallback behavior when data is missing, a webhook fails or nobody responds.</li></ul><h2>What a good outcome looks like</h2><p>The goal is a clearer path from customer intent to the next business action, with fewer silent handoff failures and enough visibility to know what happened.</p><a className="next" href={g[5]}>Explore the related solution →</a></article></main><Foot/></>}
export function Solution({slug}){const s=sols[slug]||sols['website-systems'];const demo=slug==='hvac'?'/demos/hvac-ai-front-desk':slug==='real-estate'?'/demos/luxury-real-estate':slug==='healthcare'?'/demos/healthcare-patient-experience':null;return <><Meta title={s[1]+' | ConnectiveStack'} desc={s[2]} path={'/solutions/'+slug}/><Head/><main className="seo-main"><section className="seo-hero"><span>{s[0]}</span><h1>{s[1]}</h1><p>{s[2]}</p><div className="actions">{demo&&<a className="primary" href={demo}>Try the live demo →</a>}<a href="/resources">Explore related problems →</a></div></section><section className="seo-grid"><article><small>01</small><h2>Find the failure point</h2><p>Map the current customer and data path before adding another tool.</p></article><article><small>02</small><h2>Connect the next action</h2><p>Give each inquiry a defined destination, owner, status or automated response.</p></article><article><small>03</small><h2>Test beyond the happy path</h2><p>Check mobile behavior, missing data, retries, duplicates and human handoff.</p></article><article><small>04</small><h2>Measure the real journey</h2><p>Track useful business actions instead of stopping at page views or tool activity.</p></article></section></main><Foot/></>}
export function AboutAjell(){return <><Meta title="Ajell Saliba (AJ) | Web & AI Automation Specialist | ConnectiveStack" desc="Ajell Saliba, also known as AJ, is the independent web and systems specialist behind ConnectiveStack." path="/ajell-saliba"/><Head/><main className="seo-main about-aj"><section><div><span>AJELL SALIBA / CONNECTIVESTACK</span><h1>Ajell Saliba - Web & AI Automation Specialist</h1><p className="lead">I’m Ajell “AJ” Saliba, the independent specialist behind ConnectiveStack. I work across websites, lead routing, CRM, automation, integrations, DNS and deployment.</p><p>My 11 years of professional experience span customer service, sales, quality assurance, leadership of a 17-person QA team, GoHighLevel operations, website delivery and technical systems work. Clients work directly with me from problem mapping through launch.</p><div className="actions"><a className="primary" href="https://www.linkedin.com/in/ajellsaliba" target="_blank" rel="noreferrer">LinkedIn →</a><a href="/resources">Technical guides →</a></div></div><img src="/assets/ajell-saliba.webp" alt="Ajell Saliba, AJ, web and AI automation specialist behind ConnectiveStack"/></section></main><Foot/></>}
export const guideSlugs=new Set(guides.map(g=>g[0]))
export const solutionSlugs=new Set(Object.keys(sols))
